### ISSUE TITLE
Request is empty

### ISSUE THREAD

**Issue by rockwellll** [ipinfo/rails#10]
Hi. So, i've just installed and configured the gem. Tremendous work and works perfectly. However, when i try to print the attributes for  `  puts request.env['ipinfo'].all` i get the following

```
{:ip=>"::1", :bogon=>true, :ip_address=>#<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0001/ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff>}

```

I am testing on development mode.

all other attributes are missing. i could not find out where to fix it. what's going wrong? Thanks.

**Comment by UmanShahzad** [comment]
@A7madXatab this is because you are making the request from the local environment or similar. In that environment requests will be made from a "local" IP which is considered bogon and does not have geolocation data attached to it.

If you intend on testing things, you will probably need to use a mock on requests against `ipinfo.io` to return some pre-set data, or some other method. This issue would apply to basically all languages/frameworks.

**Comment by A7madXatab** [comment]
> @A7madXatab this is because you are making the request from the local environment or similar. In that environment requests will be made from a "local" IP which is considered bogon and does not have geolocation data attached to it.
> 
> If you intend on testing things, you will probably need to use a mock on requests against `ipinfo.io` to return some pre-set data, or some other method. This issue would apply to basically all languages/frameworks.

@UmanShahzad thanks for the quick reply. Makes sense. Will do just what you suggested.
